run:
  timeout: 3m

issues:
  exclude-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - misspell
    - gosec
    - bodyclose

linters-settings:
  gosec:
    excludes:
      - G104  # unhandled errors in defers are fine
