apiVersion: v1
kind: Service
metadata:
  name: game
  namespace: gssr
spec:
  selector:
    app: game
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30300
    - name: metrics
      port: 2112
      targetPort: 2112
      nodePort: 32112
